apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-stage
  namespace: argocd
spec:
  destination:
    namespace: stage
    name: kind
  project: default
  source:
    path: helm-umbrella-chart
    repoURL: https://github.com/Mehomalk/helm_argocd/tree/main/hello-world
    targetRevision: HEAD
    helm:
      # https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#values-files
      valueFiles:
      - values-rec.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
